from docx import Document
from docx.shared import Pt

# Open existing document
doc = Document('Inventory_System_Documentation.docx')

# 6. SYSTEM FEATURES
doc.add_heading('6. SYSTEM FEATURES', 1)

doc.add_heading('6.1 Security & Authentication Features', 2)

doc.add_heading('User Authentication', 3)
doc.add_paragraph('• Unified login system for all user types')
doc.add_paragraph('• Role-based authentication (Super Admin, Admin, Staff, Supplier)')
doc.add_paragraph('• Secure password management with validation')
doc.add_paragraph('• Session management')
doc.add_paragraph('• Logout functionality')

doc.add_heading('Security Protections', 3)
doc.add_paragraph('• SQL Injection Protection: All queries use Django ORM')
doc.add_paragraph('• CSRF Protection: Built-in CSRF tokens for all forms')
doc.add_paragraph('• XSS Protection: Input validation and sanitization')
doc.add_paragraph('• Secure Headers: HSTS, X-Frame-Options, Content-Type-Nosniff')
doc.add_paragraph('• Password Validation: Multiple validators for strong passwords')

doc.add_heading('Audit Logging', 3)
doc.add_paragraph('• Complete audit trail for all user actions')
doc.add_paragraph('• IP address tracking')
doc.add_paragraph('• User agent tracking')
doc.add_paragraph('• Action types: Create, Read, Update, Delete, Login, Logout, Permission Grant/Revoke')
doc.add_paragraph('• Immutable audit logs with timestamps')
doc.add_paragraph('• Searchable and filterable audit logs')

doc.add_heading('6.2 User Management Features', 2)

doc.add_heading('User CRUD Operations', 3)
doc.add_paragraph('• Create users with role assignment')
doc.add_paragraph('• View user details with permissions and links')
doc.add_paragraph('• Update user information')
doc.add_paragraph('• Delete users (Super Admin only)')
doc.add_paragraph('• Toggle user active/inactive status')
doc.add_paragraph('• Auto-generated usernames from first/last name')

doc.add_heading('Role-Based Access Control (RBAC)', 3)
doc.add_paragraph('• Super Admin: Full system access, can manage all users')
doc.add_paragraph('• Admin: Can manage staff users and assign permissions')
doc.add_paragraph('• Staff: Basic access with assigned permissions')
doc.add_paragraph('• Supplier: Limited access to supplier portal')

doc.add_heading('Permission System', 3)
doc.add_paragraph('• Granular permissions:')
doc.add_paragraph('  - Inventory: Read, Write, Delete')
doc.add_paragraph('  - User: Read, Write, Delete')
doc.add_paragraph('  - Reports: Read, Write')
doc.add_paragraph('  - Settings: Read, Write')
doc.add_paragraph('• Permission granting/revoking')
doc.add_paragraph('• Permission expiration dates')
doc.add_paragraph('• Bulk permission updates')

doc.add_heading('User Relationships', 3)
doc.add_paragraph('• Manager-subordinate relationships')
doc.add_paragraph('• Colleague links')
doc.add_paragraph('• User link management')

doc.add_heading('6.3 Dashboard Features', 2)

doc.add_heading('Main Dashboard (Admin/Super Admin)', 3)
doc.add_paragraph('• Total products count')
doc.add_paragraph('• Total inventory value')
doc.add_paragraph('• Low stock alerts')
doc.add_paragraph('• Out of stock alerts')
doc.add_paragraph('• Finished goods statistics')
doc.add_paragraph('• Recent items with stock status')
doc.add_paragraph('• Monthly stock value trends (6-month chart)')
doc.add_paragraph('• Recent activity logs')
doc.add_paragraph('• Value change percentage')

doc.add_heading('Attendance Dashboard (Staff)', 3)
doc.add_paragraph('• Today\'s attendance record')
doc.add_paragraph('• AM/PM clock in/out buttons')
doc.add_paragraph('• Monthly calendar view')
doc.add_paragraph('• Attendance history')
doc.add_paragraph('• Today\'s production summary')
doc.add_paragraph('• Production ingredients breakdown')

doc.add_heading('Supplier Dashboard', 3)
doc.add_paragraph('• Purchase orders overview')
doc.add_paragraph('• Order status tracking')
doc.add_paragraph('• Pending approvals')
doc.add_paragraph('• Shipped orders')

doc.add_heading('6.4 Attendance/DTR Features', 2)

doc.add_heading('Time Tracking', 3)
doc.add_paragraph('• AM shift: Time In/Out')
doc.add_paragraph('• PM shift: Time In/Out')
doc.add_paragraph('• Manila timezone support')
doc.add_paragraph('• Single clock-in per shift enforcement')
doc.add_paragraph('• Real-time clock display')

doc.add_heading('Attendance Management', 3)
doc.add_paragraph('• Daily attendance records')
doc.add_paragraph('• Calendar view with attendance status')
doc.add_paragraph('• Complete/Partial/Missing indicators')
doc.add_paragraph('• Month navigation')
doc.add_paragraph('• Admin attendance overview')

doc.add_heading('Shift Scheduling', 3)
doc.add_paragraph('• Morning shift')
doc.add_paragraph('• Afternoon shift')
doc.add_paragraph('• Whole day shift')
doc.add_paragraph('• Effective date ranges')

doc.add_heading('6.5 Inventory Management Features', 2)

doc.add_heading('Item Management', 3)
doc.add_paragraph('• Auto-generated item codes (Format: YYYYMM0001)')
doc.add_paragraph('• Item categories: Ingredient, Finished Good, Packaging, Equipment')
doc.add_paragraph('• Multiple units: pcs, kg, g, L, mL, pack, box, dozen')
doc.add_paragraph('• Item descriptions')
doc.add_paragraph('• Reorder level tracking')
doc.add_paragraph('• Minimum order quantity')
doc.add_paragraph('• Active/inactive status')

doc.add_heading('Perishable Item Management', 3)
doc.add_paragraph('• Perishable flag')
doc.add_paragraph('• Shelf life in days')
doc.add_paragraph('• Expiration date tracking')
doc.add_paragraph('• Expiring soon alerts (7-day threshold)')
doc.add_paragraph('• Expired item detection')

doc.add_heading('Stock Lot Management', 3)
doc.add_paragraph('• Lot number tracking')
doc.add_paragraph('• Quantity management')
doc.add_paragraph('• Unit cost tracking')
doc.add_paragraph('• Received date')
doc.add_paragraph('• Expiration date')
doc.add_paragraph('• Supplier association')
doc.add_paragraph('• Lot notes')

doc.add_heading('Stock Movement Tracking', 3)
doc.add_paragraph('• Movement types:')
doc.add_paragraph('  - Receive Stock')
doc.add_paragraph('  - Consume Stock')
doc.add_paragraph('  - Produce Stock')
doc.add_paragraph('  - Adjust Stock')
doc.add_paragraph('  - Transfer Stock')
doc.add_paragraph('  - Spoilage')
doc.add_paragraph('• Reference numbers')
doc.add_paragraph('• Reason tracking')
doc.add_paragraph('• Detailed notes')
doc.add_paragraph('• Timestamp tracking')
doc.add_paragraph('• User tracking')

doc.add_heading('Stock Operations', 3)
doc.add_paragraph('• Stock receive with lot creation')
doc.add_paragraph('• Stock consume (FIFO - First In First Out)')
doc.add_paragraph('• Stock adjustments')
doc.add_paragraph('• Real-time stock calculations')
doc.add_paragraph('• Low stock detection')

doc.add_heading('6.6 Production Features', 2)

doc.add_heading('Recipe Management', 3)
doc.add_paragraph('• Recipe creation')
doc.add_paragraph('• Product association (finished goods only)')
doc.add_paragraph('• Yield quantity and unit')
doc.add_paragraph('• Recipe steps/instructions')
doc.add_paragraph('• Active/inactive status')
doc.add_paragraph('• Recipe cost calculation')

doc.add_heading('Recipe Items (Ingredients)', 3)
doc.add_paragraph('• Ingredient quantity')
doc.add_paragraph('• Unit specification')
doc.add_paragraph('• Loss factor percentage')
doc.add_paragraph('• Adjusted quantity calculation')
doc.add_paragraph('• Ingredient notes')

doc.add_heading('Production Workflow', 3)
doc.add_paragraph('• Recipe-based production')
doc.add_paragraph('• Automatic ingredient consumption (FIFO)')
doc.add_paragraph('• Production quantity input')
doc.add_paragraph('• Stock lot creation for finished goods')
doc.add_paragraph('• Production history')
doc.add_paragraph('• Today\'s production tracking')
doc.add_paragraph('• Ingredient usage tracking')

doc.add_heading('6.7 Purchase Order Features', 2)

doc.add_heading('Purchase Order Management', 3)
doc.add_paragraph('• Auto-generated order numbers (Format: PO-YYYYMMDD-XXXX)')
doc.add_paragraph('• QR code generation for tracking')
doc.add_paragraph('• Order status workflow:')
doc.add_paragraph('  - Draft')
doc.add_paragraph('  - Pending Approval')
doc.add_paragraph('  - Approved by Supplier')
doc.add_paragraph('  - Shipped')
doc.add_paragraph('  - Received')
doc.add_paragraph('  - Cancelled')

doc.add_heading('Purchase Order Items', 3)
doc.add_paragraph('• Item selection')
doc.add_paragraph('• Quantity ordered')
doc.add_paragraph('• Unit specification')
doc.add_paragraph('• Unit price (set by supplier)')
doc.add_paragraph('• Quantity received tracking')
doc.add_paragraph('• Subtotal calculation')

doc.add_heading('Purchase Order Workflow', 3)
doc.add_paragraph('• Create order')
doc.add_paragraph('• Submit to supplier')
doc.add_paragraph('• Supplier approval with pricing')
doc.add_paragraph('• Expected delivery date')
doc.add_paragraph('• Ship order')
doc.add_paragraph('• QR code scanning for receiving')
doc.add_paragraph('• Receive order (creates stock lots)')
doc.add_paragraph('• Order cancellation')

doc.add_heading('6.8 Supplier Portal Features', 2)

doc.add_heading('Supplier Account Management', 3)
doc.add_paragraph('• Supplier user accounts')
doc.add_paragraph('• Supplier master data (name, contact, phone, email, address)')
doc.add_paragraph('• Link user account to supplier')
doc.add_paragraph('• Supplier login')

doc.add_heading('Supplier Order Management', 3)
doc.add_paragraph('• View assigned purchase orders')
doc.add_paragraph('• Order details')
doc.add_paragraph('• Approve orders with pricing')
doc.add_paragraph('• Set expected delivery dates')
doc.add_paragraph('• Mark orders as shipped')
doc.add_paragraph('• Supplier notes')

doc.add_heading('6.9 Reporting Features', 2)

doc.add_heading('Stock Reports', 3)
doc.add_paragraph('• Current stock levels')
doc.add_paragraph('• Stock value calculations')
doc.add_paragraph('• Low stock items')
doc.add_paragraph('• Out of stock items')
doc.add_paragraph('• Stock by category')

doc.add_heading('Expiration Tracker', 3)
doc.add_paragraph('• Items expiring soon (7-day window)')
doc.add_paragraph('• Expired items')
doc.add_paragraph('• Lot-level expiration tracking')
doc.add_paragraph('• Perishable item monitoring')

doc.add_heading('Production Reports', 3)
doc.add_paragraph('• Daily production summary')
doc.add_paragraph('• Production history')
doc.add_paragraph('• Ingredient consumption tracking')

doc.add_heading('6.10 Additional Features', 2)

doc.add_heading('Search & Filtering', 3)
doc.add_paragraph('• User search (username, name, email)')
doc.add_paragraph('• Role filtering')
doc.add_paragraph('• Date range filtering')
doc.add_paragraph('• Item search')
doc.add_paragraph('• Pagination support')

doc.add_heading('API Endpoints', 3)
doc.add_paragraph('• Item lots API (JSON)')
doc.add_paragraph('• Item metadata API')
doc.add_paragraph('• Real-time data fetching')

doc.add_heading('Data Validation', 3)
doc.add_paragraph('• Input sanitization')
doc.add_paragraph('• Role hierarchy validation')
doc.add_paragraph('• Permission validation')
doc.add_paragraph('• Business rule enforcement')

doc.add_heading('Timezone Support', 3)
doc.add_paragraph('• Asia/Manila timezone')
doc.add_paragraph('• Timezone-aware datetime handling')
doc.add_paragraph('• Localized time display')

doc.add_heading('Database Features', 3)
doc.add_paragraph('• MySQL backend')
doc.add_paragraph('• UUID primary keys')
doc.add_paragraph('• Foreign key relationships')
doc.add_paragraph('• Unique constraints')
doc.add_paragraph('• Indexes for performance')

doc.add_heading('User Interface Features', 3)
doc.add_paragraph('• Responsive design')
doc.add_paragraph('• Mobile-friendly layouts')
doc.add_paragraph('• Phone access support')
doc.add_paragraph('• Network IP access (192.168.x.x)')
doc.add_paragraph('• Role-based navigation menus')
doc.add_paragraph('• Breadcrumbs')
doc.add_paragraph('• Quick access links')
doc.add_paragraph('• Dashboard widgets')

doc.add_heading('Forms', 3)
doc.add_paragraph('• CSRF-protected forms')
doc.add_paragraph('• Form validation')
doc.add_paragraph('• Error messaging')
doc.add_paragraph('• Success notifications')
doc.add_paragraph('• Bulk operations')

doc.add_page_break()

# Summary Statistics
doc.add_heading('7. SYSTEM STATISTICS', 1)
doc.add_paragraph('• Total Models: 14')
doc.add_paragraph('• Total Views: 40+')
doc.add_paragraph('• Total URL Patterns: 40+')
doc.add_paragraph('• User Roles: 4 (Super Admin, Admin, Staff, Supplier)')
doc.add_paragraph('• Permission Types: 10')
doc.add_paragraph('• Stock Movement Types: 6')
doc.add_paragraph('• Item Categories: 4')
doc.add_paragraph('• Unit Types: 8')

doc.add_page_break()

# Key Workflows
doc.add_heading('8. KEY WORKFLOWS', 1)

doc.add_heading('8.1 User Management Workflow', 2)
doc.add_paragraph('1. Create user account')
doc.add_paragraph('2. Assign role')
doc.add_paragraph('3. Grant permissions')
doc.add_paragraph('4. User logs in')
doc.add_paragraph('5. Monitor activities')
doc.add_paragraph('6. Manage permissions as needed')

doc.add_heading('8.2 Inventory Workflow', 2)
doc.add_paragraph('1. Create item')
doc.add_paragraph('2. Receive stock (create lot)')
doc.add_paragraph('3. Track lot expiration')
doc.add_paragraph('4. Monitor stock levels')
doc.add_paragraph('5. Generate reorder alerts')
doc.add_paragraph('6. Consume stock (FIFO)')

doc.add_heading('8.3 Production Workflow', 2)
doc.add_paragraph('1. Create recipe')
doc.add_paragraph('2. Add ingredients')
doc.add_paragraph('3. Initiate production')
doc.add_paragraph('4. System auto-consumes ingredients')
doc.add_paragraph('5. System creates finished goods')
doc.add_paragraph('6. View production history')

doc.add_heading('8.4 Purchase Order Workflow', 2)
doc.add_paragraph('1. Create purchase order')
doc.add_paragraph('2. Add items and quantities')
doc.add_paragraph('3. Submit to supplier (QR generated)')
doc.add_paragraph('4. Supplier approves with pricing')
doc.add_paragraph('5. Supplier ships order')
doc.add_paragraph('6. Scan QR to receive')
doc.add_paragraph('7. System creates stock lots')

doc.add_heading('8.5 Attendance Workflow', 2)
doc.add_paragraph('1. Clock in AM')
doc.add_paragraph('2. Clock out AM')
doc.add_paragraph('3. Clock in PM')
doc.add_paragraph('4. Clock out PM')
doc.add_paragraph('5. View attendance calendar')
doc.add_paragraph('6. Admin reviews records')

# Save document
doc.save('Inventory_System_Documentation.docx')
print("Complete documentation created successfully!")
print("File saved as: Inventory_System_Documentation.docx")
