# Generated by Django 5.1.3 on 2025-10-08 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shiftschedule_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ingredient', 'Ingredient'), ('finished_good', 'Finished Good'), ('packaging', 'Packaging Material'), ('equipment', 'Equipment')], max_length=20)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('pack', 'Pack'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_perishable', models.BooleanField(default=False)),
                ('shelf_life_days', models.PositiveIntegerField(default=0, help_text='Shelf life in days (0 for non-perishable)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('yield_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('pack', 'Pack'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'category': 'finished_good'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_no', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('pack', 'Pack'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_lots', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Stock Lot',
                'verbose_name_plural': 'Stock Lots',
                'db_table': 'stock_lot',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('receive', 'Receive Stock'), ('consume', 'Consume Stock'), ('produce', 'Produce Stock'), ('adjust', 'Adjust Stock'), ('transfer', 'Transfer Stock'), ('spoilage', 'Spoilage')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('pack', 'Pack'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=10)),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocklot')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movement',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stocklot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('pack', 'Pack'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=10)),
                ('loss_factor', models.DecimalField(decimal_places=2, default=0, help_text='Loss factor percentage (0-100)', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(limit_choices_to={'category': 'ingredient'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='inventory.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Item',
                'verbose_name_plural': 'Recipe Items',
                'db_table': 'recipe_item',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
