# Generated by Django 5.1.3 on 2025-10-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_recipe_stocklot_stockmovement_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
