# Generated by Django 5.1.3 on 2025-10-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.OneToOneField(blank=True, help_text='Link to supplier if this is a supplier account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('supplier', 'Supplier')], default='staff', max_length=20),
        ),
    ]
