# Generated by Django 5.1.3 on 2025-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_user_supplier_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, help_text='Recipe preparation steps', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Set by supplier during approval', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price set by supplier during approval', max_digits=10),
        ),
    ]
