# Generated by Django 5.1.3 on 2025-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_approved_at_purchaseorder_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', 'Receive Stock'), ('consume', 'Consume Stock'), ('produce', 'Produce Stock'), ('adjust', 'Adjust Stock'), ('transfer', 'Transfer Stock'), ('spoilage', 'Spoilage'), ('damage', 'Damage/Loss')], max_length=20),
        ),
    ]
